# Generated by Django 5.2.1 on 2025-05-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категорія')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва інструмента')),
                ('brand', models.CharField(default='Без бренду', max_length=50, verbose_name='Бренд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вага (кг)')),
                ('material', models.CharField(default='метал', max_length=50, verbose_name='Матеріал')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ogirok.category', verbose_name='Категорія')),
            ],
        ),
    ]
